### ISSUE TITLE
Can't add private.pem content to config

### ISSUE THREAD

**Issue by CelticWebSolutions** [tamimology/cloudflare-authelia#1]
Hi,

Whenever I add the content of private.pem to my config file, I get an error on startup saying

time="2023-03-03T18:57:27Z" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'identity_providers.oidc.issuer_private_key': could not decode to a *rsa.PrivateKey: failed to parse PEM block containing the key"

Is there a special way of doing this?  I've ensured each of the pem content all starts with the same spacing for each line and passed the config through https://www.yamllint.com to check it's OK.  I'm now at a loss, any suggestions what I may be doing wrong?

Thanks in advance for your help.

**Comment by tamimology** [comment]
It seems you either have copied and pasted the pem contents incorrectly into the configuration, or you have issue generating the pem file

For the first, did you keep the lines where it says "---Begin..." and "---End..." and had the contents pasted in between?

For the second, did you make sure you used the correct PID and GID when generating the pem file? Those need to correspond to the same PID and GID you used in creating the authelia container

It is useful to share the configuration file you have (just change some random letters and numbers in the pem and all secrets you got to mask them)

**Comment by tamimology** [comment]
> Hi,
> 
> Whenever I add the content of private.pem to my config file, I get an error on startup saying
> 
> time="2023-03-03T18:57:27Z" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'identity_providers.oidc.issuer_private_key': could not decode to a *rsa.PrivateKey: failed to parse PEM block containing the key"
> 
> Is there a special way of doing this?  I've ensured each of the pem content all starts with the same spacing for each line and passed the config through https://www.yamllint.com to check it's OK.  I'm now at a loss, any suggestions what I may be doing wrong?
> 
> Thanks in advance for your help.

I haven't heard from you again, shall I consider the issue is resolved then?
